osx_image: xcode11
language: swift
script:
    - set -o pipefail && xcodebuild test -project Basic-Example/ExampleAlert.xcodeproj -scheme ExampleAlertUITests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.0,name=iPad Pro (12.9-inch) (3nd generation)'